FROM ubuntu:jammy

RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    unzip \
    less \
    vim \
    nano \
    wget \
    jq \
    nginx\
    groff

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    rm awscliv2.zip && \
    ./aws/install && \
    rm -rf ./aws

RUN wget https://github.com/99designs/aws-vault/releases/download/v6.6.0/aws-vault-linux-amd64 && \
    chmod +x aws-vault-linux-amd64 && \
    mv aws-vault-linux-amd64 /usr/bin/aws-vault

COPY --from=hairyhenderson/gomplate:stable /gomplate /bin/gomplate

ENV AWS_VAULT_BACKEND=file
ENV AWS_VAULT_FILE_PASSPHRASE=password
ENV AWS_REGION=eu-central-1

ENTRYPOINT [ "/opt/instruqt/aws-entrypoint.sh" ]
COPY aws-entrypoint.sh /opt/instruqt/

COPY assets/  /var/www/html/assets/
COPY index.html.tmpl /opt/instruqt/