FROM ubuntu:jammy

RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    unzip \
    less \
    vim \
    nano \
    wget \
    jq \
    nginx

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    rm awscliv2.zip && \
    ./aws/install && \
    rm -rf ./aws

COPY --from=hairyhenderson/gomplate:stable /gomplate /bin/gomplate

ENTRYPOINT [ "/opt/instruqt/aws-entrypoint.sh" ]
COPY aws-entrypoint.sh /opt/instruqt/

COPY assets/  /var/www/html/assets/
COPY index.html.tmpl /opt/instruqt/